CREATE DATABASE LACIOPPA_DB
GO
USE LACIOPPA_DB
GO

-------TABLAS-------
CREATE TABLE TECNICOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	USUARIO VARCHAR(10) NOT NULL,
	CONTRASEÑA NVARCHAR(10) NOT NULL,
	IDPERFIL INT NOT NULL FOREIGN KEY REFERENCES PERFILES_TECNICOS(ID),
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	DNI VARCHAR(10) NOT NULL,
	SUELDO MONEY NULL,
	ESTADO BIT NOT NULL
	)
	GO
CREATE TABLE CLIENTES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	DNI VARCHAR(10) NOT NULL,
	DIRECCION VARCHAR(15) NULL,
	LOCALIDAD VARCHAR(15) NULL,
	TELEFONO VARCHAR(10) NULL,
	MAIL VARCHAR(50) NULL,
	ESTADO BIT NOT NULL
	)
	GO
CREATE TABLE REPUESTOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CODIGO NVARCHAR(50) NOT NULL,
	NOMBRE NVARCHAR(30) NOT NULL,
	PRECIO MONEY NOT NULL CHECK(PRECIO > 0),
	IDCATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS_REPUESTOS(ID),
	ESTADO BIT NOT NULL
	)
	

	GO
CREATE TABLE CATEGORIAS_REPUESTOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(15) NOT NULL,
	ESTADO BIT NOT NULL
	)
ALTER TABLE CATEGORIAS_REPUESTOS
ALTER COLUMN NOMBRE NVARCHAR(45)

	GO
CREATE TABLE PERFILES_TECNICOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(15) NOT NULL,
	ESTADO BIT NOT NULL,
	)
	GO
CREATE TABLE EQUIPOS(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NUMEROSERIE NVARCHAR(50) NOT NULL,
	MARCA NVARCHAR(50) NOT NULL,
	MODELO NVARCHAR(50) NULL
	)

CREATE TABLE ESTADOS_REPARACION(
	ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	NOMBRE VARCHAR(15) NOT NULL
	)

GO
CREATE TABLE REPARACIONES(
--entrada
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ORDEN BIGINT NOT NULL,
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID),
	IDEQUIPO INT NOT NULL FOREIGN KEY REFERENCES EQUIPOS(ID),
	IDTECNICO INT NOT NULL FOREIGN KEY REFERENCES TECNICOS(ID),
	IDESTADO INT NOT NULL FOREIGN KEY REFERENCES ESTADOS_REPARACION(ID),
	PROBLEMA NVARCHAR(MAX) NULL,
	FECHA_ENTRADA smalldatetime NOT NULL,
--salida
	--TABLA REPARACIONES X REPUESTOS HACER INNER JOIN PARA MOSTRARLO EN EL PROGRAMA
	INFORME NVARCHAR(MAX) NULL,
	PRECIO MONEY NULL,
	FECHA_SALIDA smalldatetime NULL,
)


GO
CREATE TABLE REPUESTOS_POR_REPARACIONES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDREPARACIONES INT not NULL FOREIGN KEY REFERENCES REPARACIONES(ID),
	IDREPUESTO INT not NULL FOREIGN KEY REFERENCES REPUESTOS(ID)
)



-----------QUERYS-----------

--QUERY PARA AUTONUMERICO
SELECT TOP 1 ID FROM EQUIPOS ORDER BY ID DESC

--opcion 1
SELECT R.ORDEN, CLI.NOMBRE, CLI.APELLIDO, CLI.TELEFONO, EQ.NUMEROSERIE AS 'NUMERO DE SERIE' ,EQ.MARCA, EQ.MODELO, TEC.USUARIO AS 'TECNICO', R.FECHA_ENTRADA AS 'ENTRADA', R.PROBLEMA, ER.NOMBRE AS 'ESTADO'
FROM REPARACIONES AS R
INNER JOIN CLIENTES AS CLI ON R.IDCLIENTE = CLI.ID
INNER JOIN EQUIPOS AS EQ ON R.IDEQUIPO = EQ.ID
INNER JOIN TECNICOS AS TEC ON R.IDTECNICO = TEC.ID
INNER JOIN ESTADOS_REPARACION AS ER ON R.IDESTADO = ER.ID
WHERE R.IDESTADO = 1


--EN REPARACION
SELECT R.ORDEN, CLI.NOMBRE, CLI.APELLIDO, CLI.TELEFONO,EQ.MARCA, EQ.MODELO, R.PROBLEMA, R.FECHA_ENTRADA AS 'ENTRADA'
FROM REPARACIONES AS R
INNER JOIN CLIENTES AS CLI ON R.IDCLIENTE = CLI.ID
INNER JOIN ESTADOS_REPARACION AS ER ON R.IDESTADO = ER.ID
INNER JOIN EQUIPOS AS EQ ON R.IDEQUIPO = EQ.ID
WHERE ER.ID = 1





--TXTBOX (BuscarReparacion2)
SELECT EQ.NUMEROSERIE AS 'NUMERO DE SERIE', EQ.MARCA, EQ.MODELO, TEC.USUARIO AS 'TECNICO'
FROM REPARACIONES AS R
INNER JOIN EQUIPOS AS EQ ON R.IDEQUIPO = EQ.ID
INNER JOIN TECNICOS AS TEC ON R.IDTECNICO = TEC.ID
INNER JOIN ESTADOS_REPARACION AS ER ON R.IDESTADO = ER.ID
WHERE ER.ID = 1



